name: Deploy C2C Platform

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to VB Server via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ia SSH Action
        run: |
          cd /home/tung/c2c-platform-run
          bash scripts/deploy.sh